# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fed1c0b8ee8b3f4ab026aeb37eb4ef10"
application_url = "https://bolt-situated-geology-shaft.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-31"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_product_listings,write_customers,write_products"

[auth]
redirect_urls = [
  "https://bolt-situated-geology-shaft.trycloudflare.com/auth/callback",
  "https://bolt-situated-geology-shaft.trycloudflare.com/auth/shopify/callback",
  "https://bolt-situated-geology-shaft.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
