# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93ecc33ae551fe8adbec24fb44922f97"
application_url = "https://might-shield-manhattan-toolkit.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-49"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,write_customers,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://might-shield-manhattan-toolkit.trycloudflare.com/auth/callback",
  "https://might-shield-manhattan-toolkit.trycloudflare.com/auth/shopify/callback",
  "https://might-shield-manhattan-toolkit.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
