# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa523b92993937330f4236f6e02882e7"
application_url = "https://mental-el-np-ultimately.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-29"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_product_listings,write_customers,write_products"

[auth]
redirect_urls = [
  "https://mental-el-np-ultimately.trycloudflare.com/auth/callback",
  "https://mental-el-np-ultimately.trycloudflare.com/auth/shopify/callback",
  "https://mental-el-np-ultimately.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
