# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1d0c7ca131b5d572ddcebc610abcbe6"
application_url = "https://col-monsters-tribes-lightning.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-22"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://col-monsters-tribes-lightning.trycloudflare.com/auth/callback",
  "https://col-monsters-tribes-lightning.trycloudflare.com/auth/shopify/callback",
  "https://col-monsters-tribes-lightning.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
